### ISSUE TITLE
Padding differences against MRI for cipher modes such as OFB

### ISSUE THREAD

**Issue by iamasmith** [jruby/jruby-openssl#13]
I'm working on an RPC interface at the moment with the POC piece in Ruby, but I wrote a Java client.

I found that using bf-ofb cipher that MRI Ruby used no padding, not going to get into it should or it shouldn't but the current default for MRI is not to pad with the bf-ofb Cipher, hence my JCE implementation uses Cipher.getInstance("Blowfish/OFB64/NoPadding") and this works quite happily with MRI Ruby on default settings and no cipher.padding = 0 added.

The documentation is a little vague but the behaviour is definitely there that padding isn't added by MRI but on JRuby it seems to default the other way.

I did find an artical, way back (can't find it now) that states that OFB shouldn't use padding but I'm not going to get into that since this seems to be the behaviour for MRI Ruby.

I've just been more explicit in my code and added cipher.padding = 0 to my code but if you are interested, for these modes, theres a subtle different.
##

**Comment by dgolombek** [comment]
I just ran into this as well. I believe the issue is that OFB, CFB, CFB8, and CTR modes should use padding type of NoPadding. There's already a TODO to this effect at https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/Cipher.java#L559-L562

I believe that ECB SHOULD have padding, despite the comment there already.

**Comment by dgolombek** [comment]
I opened a bug with BouncyCastle discussing this as well (bcgit/bc-java#291), but I believe the true failure is here in JRuby OpenSSL. Note that this is a incompatibility with MRI -- there's no way in MRI to add padding to CFB/OFB/CTR modes, since OpenSSL won't do so even if asked (cipher.set_padding = 1). 

I'm happy to work on a fix if you agree with this.

**Comment by kares** [comment]
@dgolombek makes sense - feel free to go for it
