### ISSUE TITLE
Calling a method whose signature changed in JRuby 9.3

### ISSUE THREAD

**Issue by headius** [jruby/jruby-openssl#245]
It looks like a change I made to RubyArray#collect (accidentally) has caused the 0.12.0 release to be incompatible with JRuby 9.2:

https://github.com/jruby/jruby/commit/e849caf1e7329ed1fe196287882866a624812def

I did not notice that the return types changed, which is sufficient to break any code that has compiled against 9.3 and tries to call 9.2, or vice versa.

The original signature should probably be restored for compatiblity with 9.2, but in the interim we will probably want to work around it in jruby-openssl so it works on the bad 9.3 releases as well as 9.2 and the fixed 9.3.4+ releases.

**Comment by kares** [comment]
I see, my bad not testing enough - the problem is CI tests we're broken (also Travis broke at some point).
There in better shape now but still needs house-keeping work, which I lack these days to spent on JOSSL :disappointed:

Here I was trying to leverage some array sharing, which is internal (`RubyArray#makeShared`) using the [`collect`](https://github.com/jruby/jruby-openssl/blob/v0.12.0/src/main/java/org/jruby/ext/openssl/SSLContext.java#L530).

Definitely address this for a quick 0.12.1 - it's just one place and sharing itself isn't super important.

**Comment by headius** [comment]
I pushed jruby/jruby#7056 to restore the old signature and add some new explicit API entry points. `collectCommon` goes away again and `collectArray` and `collectEnum` handle the two separate paths.

For 9.3.0 through 9.3.3 the only migration path might be to use `collect19` which is deprecated, but reflects the new `collect` logic while retaining the same `IRubyObject` signature throughout all 9.2 and 9.3 releases.

**Comment by kares** [comment]
thanks, we won't really need any changes to have 9.3 supported and working.
the `RubyArray#collect` was only present in JOSSL 0.12.0 (which got yanked), 0.12.1 will avoid using `collect` (and will simply `RubyArray#dup`) - all is expected to be working on any JRuby 9.2/9.3 versions ...

**Comment by headius** [comment]
Ok, fingers crossed no other libraries run into the binary incompatiblity in 9.3.0-9.3.3.
