### ISSUE TITLE
FIPS-140 support?

### ISSUE THREAD

**Issue by wbushey** [jruby/jruby-openssl#259]
Hello, I'm working on a jRuby application that we need to be able to build and run in FIPS-140 mode. We've run into an issue building the application on a host that's running in FIPS-140 mode: any attempt to use jRuby to establish an SSL/TLS connection, including when attempting to install gems, results in a `SSL Context not available` error.

In our efforts to debug this issue, we've tried to search for information about jruby-openssl's support for FIPS-140, but we've found there isn't a lot available online. The most definitive information we've been able to find are these `FIPS mode not implemented on JRuby-OpenSSL` [warnings in the get/set_fips_mode methods in the OpenSSL class](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/OpenSSL.java#L180), which seems to indicate that jRuby-OpenSSL does not support FIPS-140 mode. But I'm wondering if there's any more information about jRuby-OpenSSL and FIPS-140. Is there any way to enable FIPS-140 mode using jRuby-OpenSSL? Are there any plans to support FIPS-140 in jRuby-OpenSSL?

**Comment by kares** [comment]
Hey, unfortunately there hasn't been any development towards FIPS support.
This is mostly due lack to dedicated developers on the JRuby eco-system atm.

The FIPS support would in large depend on [Bouncy-Castle](https://www.bouncycastle.org/fips_faq.html#JAVA) and the details of loading JOSSL with a separate set on (FIPS certified) .jar files would need to be figured out - the core code would need to adapted to make sure it can work with both set of .jar files.

In terms of plans, honestly I do not have any plans and I am not aware of any large organization potentially investing time or resources into making that happen - esp. since the scope is unclear.

**Comment by wbushey** [comment]
Gotcha; that makes a lot of sense. Thanks for answering my question!

**Comment by yweiy10** [comment]
Hey @kares ,
I'd like to invest some time here to verify if I can switch the bouncycastle jars to be fips-validated ones. My application is mainly in JRuby and we recently got a request for FIPS compliance. So I don't think I have another choice but to fix the jRuby-openssl and have a FIPS version of it at least. Is that right?

And for the development, I'd like to understand how I can test thoroughly after switching the bc dependencies. Is unit test in the codebase decent? 

Thanks for your help!
